
import static java.awt.event.PaintEvent.UPDATE;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static javax.swing.event.TableModelEvent.UPDATE;
import javax.swing.table.DefaultTableModel;
import static jdk.nashorn.internal.runtime.PropertyDescriptor.SET;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sksingh
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        createTables();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        libpswd = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        libpswd1 = new javax.swing.JPasswordField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel17 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jButton19 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setForeground(new java.awt.Color(0, 102, 102));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.jpg"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Curlz MT", 1, 48)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("LIBRARY INFORMATION SYSTEM");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 0, 153));
        jLabel14.setText("MOVE THROUGH THE TABS TO AVAIL THE FUNCTIONS OF THE SYSTEM");

        jLabel15.setText("DESIGNED BY SKS and ACH");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(194, 194, 194))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel14)
                        .addGap(119, 119, 119)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(124, 124, 124)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 332, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(113, 113, 113)))
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
        );

        jTabbedPane1.addTab("HOME PAGE", jPanel2);

        jPanel5.setBackground(new java.awt.Color(153, 204, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ENTER PASSWORD");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 219, 234, 40));

        libpswd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        libpswd.setForeground(new java.awt.Color(153, 51, 0));
        libpswd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        libpswd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                libpswdMouseClicked(evt);
            }
        });
        jPanel5.add(libpswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 217, 301, 40));

        jButton1.setBackground(new java.awt.Color(153, 204, 255));
        jButton1.setFont(new java.awt.Font("Baskerville Old Face", 0, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 51));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PASSWORD1.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 190, 116, 100));

        jButton2.setFont(new java.awt.Font("Baskerville Old Face", 0, 20)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 51, 0));
        jButton2.setText("CHANGE PASSWORD");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, 250, 50));

        jButton3.setBackground(new java.awt.Color(153, 204, 255));
        jButton3.setFont(new java.awt.Font("Baskerville Old Face", 0, 20)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 153));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/redister here.jpg"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 490, 105, -1));

        jLabel10.setFont(new java.awt.Font("Algerian", 1, 28)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("LIBRARIAN LOGIN");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 282, 42));

        jButton4.setBackground(new java.awt.Color(204, 255, 255));
        jButton4.setFont(new java.awt.Font("Chiller", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 102, 51));
        jButton4.setText("DO YOUR DUTIES");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 360, 146, 50));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logout-icon (1).png"))); // NOI18N
        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 30, 87, 99));

        jPasswordField1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(0, 102, 51));
        jPasswordField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseClicked(evt);
            }
        });
        jPanel5.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 520, 301, 42));

        jLabel16.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 102, 51));
        jLabel16.setText("ENTER NEW PASSWORD");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 523, 326, 38));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LIBRARIAN.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 770));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 80, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("LIBRARIAN SECTION", jPanel1);

        jPanel6.setBackground(new java.awt.Color(153, 204, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(204, 204, 255));
        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ENTER PASSWORD");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 217, 234, 40));

        libpswd1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        libpswd1.setForeground(new java.awt.Color(153, 51, 0));
        libpswd1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        libpswd1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                libpswd1MouseClicked(evt);
            }
        });
        jPanel6.add(libpswd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 215, 301, 40));

        jButton6.setBackground(new java.awt.Color(153, 204, 255));
        jButton6.setFont(new java.awt.Font("Baskerville Old Face", 0, 20)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 153, 51));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PASSWORD1.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 180, 116, 100));

        jButton7.setFont(new java.awt.Font("Baskerville Old Face", 0, 20)); // NOI18N
        jButton7.setForeground(new java.awt.Color(204, 51, 0));
        jButton7.setText("CHANGE PASSWORD");
        jButton7.setEnabled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, 250, 50));

        jButton8.setBackground(new java.awt.Color(153, 204, 255));
        jButton8.setFont(new java.awt.Font("Baskerville Old Face", 0, 20)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 0, 153));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/redister here.jpg"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 490, 105, -1));

        jLabel12.setFont(new java.awt.Font("Algerian", 1, 28)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 102));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("CLERK LOGIN");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 22, 282, 42));

        jButton9.setBackground(new java.awt.Color(204, 255, 255));
        jButton9.setFont(new java.awt.Font("Chiller", 1, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 102, 51));
        jButton9.setText("DO YOUR DUTIES");
        jButton9.setEnabled(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 360, 146, 50));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logout-icon (1).png"))); // NOI18N
        jButton10.setEnabled(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1219, 22, 87, 99));

        jPasswordField2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jPasswordField2.setForeground(new java.awt.Color(0, 102, 51));
        jPasswordField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField2MouseClicked(evt);
            }
        });
        jPanel6.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 519, 301, 42));

        jLabel17.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 255, 255));
        jLabel17.setText("ENTER NEW PASSWORD");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 521, 326, 38));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clerk sec.jpg"))); // NOI18N
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1370, 790));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 100, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("CLERK SECTION", jPanel3);

        jPanel11.setBackground(new java.awt.Color(153, 204, 255));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton19.setFont(new java.awt.Font("Baskerville Old Face", 0, 20)); // NOI18N
        jButton19.setForeground(new java.awt.Color(0, 153, 51));
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(895, 269, 99, 88));

        jLabel11.setFont(new java.awt.Font("Algerian", 1, 28)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("MEMBER LOGIN");
        jPanel11.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 282, 42));

        jTextField3.setFont(new java.awt.Font("Yu Gothic", 1, 20)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(0, 102, 51));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel11.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(739, 154, 381, 40));

        jLabel8.setBackground(new java.awt.Color(51, 255, 204));
        jLabel8.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("LOGIN ID");
        jPanel11.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 237, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wel mem.jpg"))); // NOI18N
        jPanel11.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MembersGraphic2.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel11.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1350, 730));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1370, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 55, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 55, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("MEMBER'S SECTION", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Connection conn = null;
	        try {
	           String userName = "root";
	           String password = "root";
                   String url = "jdbc:derby://localhost:1527/lis";
                   Class.forName("org.apache.derby.jdbc.ClientDriver").newInstance();
	           conn = DriverManager.getConnection(url, userName, password);
          
                   String selectSQL = "SELECT password FROM librarian";
	           PreparedStatement preparedStatement = conn.prepareStatement(selectSQL);
                   String pwd = libpswd.getText();
//	           preparedStatement.setString(1, pwd);
	           ResultSet rs = preparedStatement.executeQuery();
                   
	           while(rs.next()){
                       if(rs.getInt("password") == Integer.parseInt(pwd)){ //getInt("columnname") is used to get the data value stored in column of the row
                         jButton2.setEnabled(true);
                         jButton3.setEnabled(true);
                         jButton4.setEnabled(true);
                         jButton1.setEnabled(false);
                         jButton5.setEnabled(true);
                         jPasswordField1.setEnabled(true);
                       }
                       else
                       JOptionPane.showMessageDialog(null, "wrong password");
                   }
                   

	           rs.close();
	           conn.close();
	        }
	        catch (Exception e) {
	           System.out.print("Error: " + e.toString());
	        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        databaseLib();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void libpswdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libpswdMouseClicked
        libpswd.setText("");
    }//GEN-LAST:event_libpswdMouseClicked

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        Connection conn = null;
        Statement stmt = null;
        ResultSet rs;
	        try {
	           String userName = "root";
                  String password = "root";
                  String url = "jdbc:derby://localhost:1527/lis";
                  Class.forName("org.apache.derby.jdbc.ClientDriver").newInstance();
	           conn = DriverManager.getConnection(url,userName, password);
                   String selectSQL1 = "select * from memberrecord";
                   stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
	           rs=stmt.executeQuery(selectSQL1);
                   int c=0;
                   if(jTextField3.getText().equals(""))
                       
                       JOptionPane.showMessageDialog(null, "You have not entered your login ID");
                   else{
                       
                   while(rs.next()){  
                      
                       if(rs.getString(3).equals(jTextField3.getText())){
                          
                        new member(rs.getString(3)).setVisible(true);
                        
                       
                        setVisible(false);
                        c =1;System.out.println("bbbbbbbbbbbbbbbbbbbbbbb");
                        break;
                       
                       }                 
                       
                   }
                   if(c==0){
                       JOptionPane.showMessageDialog(null, "YOU ARE NOT MEMBER");
                   }
                   rs.close();
                   conn.close();
                   }
                }
                catch (Exception event) {
	               	System.out.println(event);
	                System.out.print("Error inserting record.");
	        }
        
                
        
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         Connection conn = null;
         Statement stmt = null;
         int i = 0;
         ResultSet rs;
	        try {
	           String userName = "root";
                  String password = "root";
                  String url = "jdbc:derby://localhost:1527/lis";
                  Class.forName("org.apache.derby.jdbc.ClientDriver").newInstance();
	           conn = DriverManager.getConnection(url,userName, password);
                   String selectSQL1 = "select * from librarian";System.out.println("aaaaaaaaaaaa");
                    stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
	           rs=stmt.executeQuery(selectSQL1);
                   while(rs.next()){
                       
                       rs.deleteRow();                     
                       JOptionPane.showMessageDialog(null, "ENTER THE NEW PASSWORD BELOW");
                   }
                   rs.close();
                   conn.close();

                }
                catch (Exception event) {
	               	System.out.println(event);
	                System.out.print("Error inserting record.");
	                        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new librarian().setVisible(true);
        setVisible(false);
        JOptionPane.showMessageDialog(null, "SUCCESSFULLY Logged in.");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
                         jButton2.setEnabled(false);
                         jButton3.setEnabled(false);
                         jButton4.setEnabled(false);
                         jButton1.setEnabled(true);
                         jButton5.setEnabled(false);
                         libpswd.setText("");
                         jPasswordField1.setEnabled(false);
                         jPasswordField1.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void libpswd1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libpswd1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_libpswd1MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
                Connection conn = null;
	        try {
	           String userName = "root";
                  String password = "root";
                  String url = "jdbc:derby://localhost:1527/lis";
                  Class.forName("org.apache.derby.jdbc.ClientDriver").newInstance();
	           conn = DriverManager.getConnection(url, userName, password);
          
                   String selectSQL = "SELECT password FROM clerk WHERE password LIKE ?";
	           PreparedStatement preparedStatement = conn.prepareStatement(selectSQL);
                   String pwd = libpswd1.getText();
	           preparedStatement.setString(1, pwd);
	           ResultSet rs = preparedStatement.executeQuery();
                   
	           if(rs.next()){
                         jButton7.setEnabled(true);
                         jButton8.setEnabled(true);
                         jButton9.setEnabled(true);
                         jButton6.setEnabled(false);
                         jButton10.setEnabled(true);
                         jPasswordField2.setEnabled(true);
                   }
                   else
                       JOptionPane.showMessageDialog(null, "wrong password");

	           rs.close();
	           conn.close();
	        }
	        catch (Exception e) {
	           System.out.print("Error: " + e.toString());
	        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Connection conn = null;
         Statement stmt = null;
         int i = 0;
         ResultSet rs;
	        try {
	          String userName = "root";
                  String password = "root";
                  String url = "jdbc:derby://localhost:1527/lis";
                  Class.forName("org.apache.derby.jdbc.ClientDriver").newInstance();
	           conn = DriverManager.getConnection(url,userName, password);
                   String selectSQL1 = "select * from clerk";System.out.println("aaaaaaaaaaaa");
                    stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
	           rs=stmt.executeQuery(selectSQL1);
                       while(rs.next()){
                       
                       rs.deleteRow();                     
                       JOptionPane.showMessageDialog(null, "ENTER THE NEW PASSWORD BELOW");
                   }
                   rs.close();
                   conn.close();

                }
                catch (Exception event) {
	               	System.out.println(event);
	                System.out.print("Error inserting record.");
	                        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        databaseclk();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        new clerk().setVisible(true);
        setVisible(false);
        JOptionPane.showMessageDialog(null, "SUCCESSFULLY Logged in.");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jPasswordField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseClicked
        jPasswordField1.setText("");
    }//GEN-LAST:event_jPasswordField1MouseClicked

    private void jPasswordField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField2MouseClicked
        jPasswordField2.setText("");
    }//GEN-LAST:event_jPasswordField2MouseClicked

    void databaseLib(){
        String details;
	details=jPasswordField1.getText();
	System.out.println(details);
	int i = 0;                
	Connection conn = null;
	try {
              String userName = "root";
	      String password = "root";
              String url = "jdbc:derby://localhost:1527/lis";
              Class.forName("org.apache.derby.jdbc.ClientDriver").newInstance();
              conn = DriverManager.getConnection(url, userName, password);
              String st = "select * from librarian";
              Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
              ResultSet rs = stmt.executeQuery(st);
              while(rs.next()){
                  i++;
              }
                if(i < 1){
              
                    if(jPasswordField1.getText().equals("")){
                 JOptionPane.showMessageDialog(null, "PASSWORFIELD IS EMPTY");
                    }
                    else{
                        PreparedStatement preparedStatement = null;
		String ps = "insert into librarian(password,serial)" +
				                      " values" +"(?,?)";

		preparedStatement = conn.prepareStatement(ps);
		preparedStatement.setString(1,details);
		preparedStatement.setInt(2,1);
                preparedStatement.executeUpdate();                
		System.out.println("Record added.");
                JOptionPane.showMessageDialog(null, "REGISTERED SUCESSFULLY");
                jButton1.setEnabled(true);
                    }
                       
                  }
                  else
                     JOptionPane.showMessageDialog(null, "ONE LIBRARIAN IS ALREAY REGISTERED");
                  rs.close();
                  conn.close();
        }
        catch (Exception event) {
	               	System.out.println(event);
	                System.out.print("error inserting record");
	                        }
    }
    
    void databaseclk(){
        String details;
	details=jPasswordField2.getText();
	System.out.println(details);
	int i = 0;    
	Connection conn = null;
	try {
              String userName = "root";
	      String password = "root";
              String url = "jdbc:derby://localhost:1527/lis";
              Class.forName("org.apache.derby.jdbc.ClientDriver").newInstance();
              conn = DriverManager.getConnection(url, userName, password);
//              String table = "CREATE TABLE clerk" + "(password INTEGER," + "serial INTEGER not null," +"PRIMARY KEY (serial))";
              String st = "select * from clerk";
              Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                                                                        ResultSet.CONCUR_READ_ONLY);
              
//              stmt.executeUpdate(table);
              ResultSet rs = stmt.executeQuery(st);
              while(rs.next()){
                  i++;
              }
              
                  if(i < 1){

                       if(jPasswordField2.getText().equals("")){
                 JOptionPane.showMessageDialog(null, "PASSWORFIELD IS EMPTY");
                    }
                    else{
                        PreparedStatement preparedStatement = null;
		String ps = "insert into clerk(password,serial)" +
				                      " values" +"(?,?)";

		preparedStatement = conn.prepareStatement(ps);
		preparedStatement.setString(1,details);
		preparedStatement.setInt(2,1);
                preparedStatement.executeUpdate();                
		System.out.println("Record added.");
                JOptionPane.showMessageDialog(null, "REGISTERED SUCESSFULLY");
                jButton6.setEnabled(true);
                    }
                      
                  }
                  else
                     JOptionPane.showMessageDialog(null, "ONE CLERK IS ALREAY REGISTERED"); 
                  
                  rs.close();
                  conn.close();
                  }
        
        catch (Exception event) {
	               	System.out.println(event);
	                System.out.print("Error inserting record.");
	                        }
    }
    
    void createTables(){
        Connection conn = null;
        try{
        String userName = "root";
	      String password = "root";
              String url = "jdbc:derby://localhost:1527/lis";
              Class.forName("org.apache.derby.jdbc.ClientDriver").newInstance();
              conn = DriverManager.getConnection(url, userName, password);
              String table_clerk = "CREATE TABLE clerk" + "(password INTEGER," + "serial INTEGER not null," +"PRIMARY KEY (serial))";
              String table_librarian = "CREATE TABLE librarian" + "(password INTEGER," + "serial INTEGER not null," +"PRIMARY KEY (serial))";
              String table_memberrecord = "CREATE TABLE memberrecord" + "(serial INTEGER not null," + "name varchar(255),"+"id varchar(255),"+"emailid varchar(255)," +"PRIMARY KEY (serial))";
              Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
              stmt.executeUpdate(table_memberrecord);
              stmt.executeUpdate(table_clerk);
              stmt.executeUpdate(table_librarian);
              
        }
        catch(Exception event){
            System.out.println(event);
        }
    }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JPasswordField libpswd;
    private javax.swing.JPasswordField libpswd1;
    // End of variables declaration//GEN-END:variables
 
}
